function trainTbl = generateTrainTbl(imgPropsForGradingTbl)

%% Generate examples for ML model training
% The selected predictors are intesity weighted mean and area of the following regions:
% "cleaned" bowel, all the bowel, bowel dark holes, bowel bones, periphery bones  

% Input:  imgPropsForGradingTbl - table of the bowel image properties
%                                 (generated by getPropsForGrading)
% Output: trainTbl              - training table with the predictors in
%                                 columns. The last column is ground truth labels.

%TODO: 1. The generated means of intensity are not all between 0-1.
%      2. Some of the generated areas are not compatible relative one to
%         another.

tbl = imgPropsForGradingTbl;
origGrade = 4;  % the grades for images from the non-ML solution

nSamp = 1500;   % samples per class to be generated

% Generate examples for all the grades (0-6)
trainTbl_0 = genTrainTbl4SpecGrade(tbl, origGrade, 0, nSamp/3);
trainTbl_1 = genTrainTbl4SpecGrade(tbl, origGrade, 1, nSamp);
trainTbl_2 = genTrainTbl4SpecGrade(tbl, origGrade, 2, nSamp);
trainTbl_3 = genTrainTbl4SpecGrade(tbl, origGrade, 3, nSamp);
trainTbl_4 = genTrainTbl4SpecGrade(tbl, origGrade, 4, nSamp);
trainTbl_5 = genTrainTbl4SpecGrade(tbl, origGrade, 5, nSamp);
trainTbl_6 = genTrainTbl4SpecGrade(tbl, origGrade, 6, nSamp/3);

% Special cases (grades 0 and 6)
trainTbl_6_2 = genTrainTbl4Grade_6(tbl, origGrade, (nSamp/3)*2);
trainTbl_0_2 = genTrainTbl4Grade_0(tbl, origGrade, (nSamp/3)*2);

% Full table
trainTbl = [trainTbl_0; trainTbl_0_2; trainTbl_1; trainTbl_2; trainTbl_3;...
    trainTbl_4; trainTbl_5; trainTbl_6; trainTbl_6_2];
